safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Lennex ZInyando"
description: "My personal blog"
baseurl: ""
url: "http://zinyando.com" # replace by your site's url
twitter_username: zinyando
github_username:  zinyando # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Lennex Zinyando"
address: "5764 Kamba St, <br>Zimre Park, <br>Ruwa, <br>Zimbabwe"
email: "brizdigital@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
